module HPIPM

# Low-level C bindings (auto-generated by Clang.jl; see ../gen/).
# Pulls in `using HPIPM_jll` and the `libhpipm` handle.
include("LibHPIPM.jl")
using .LibHPIPM

# Re-export the solver mode / status enums for convenience.
using .LibHPIPM: SPEED_ABS, SPEED, BALANCE, ROBUST
using .LibHPIPM: hpipm_mode, hpipm_status

include("memory.jl")
include("dense_qp.jl")
include("ocp_qp.jl")
include("moi_wrapper.jl")

export DenseQP, OCPQP
export set!, solve!, solve
export set_g!, set_b!, set_H!, set_A!, set_C!

end # module HPIPM
