# Autogenerated-style wrapper for HPIPM_jll, x86_64-linux-gnu
export libhpipm

JLLWrappers.@generate_wrapper_header("HPIPM")
JLLWrappers.@declare_library_product(libhpipm, "libhpipm.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libhpipm,
        "lib/libhpipm.so",
        RTLD_LAZY,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
